Runs a basic add test in Java
`InternalException` isn't checked so it can't be caught, and with the
full port of
https://github.com/mozilla/uniffi-rs/blob/main/examples/arithmetic/tests/bindings/test_arithmetic.kts
I'm getting a `NoClassDefFoundError: com/sun/jna/Structure`.